In [1]:
# 1.1 unpacking
l = (1,2)
a, b = l
print(a)
print(b)

f = (1,2,4)
try:
    a,b = f
except ValueError as e:
    print("too many value")

f = [1,2,3]
a,v,c = f
print(a, v, c)

1
2
too many value
1 2 3


In [2]:
# arbitrary length lists

f = range(6)
a,b,*c,d = f # use the star expression to unpack everything in-between
print(a) 
print(b)
print(c)
print(d) # last elements

head, *tail = f

# can split into head and tail like other languages
# (haskell)
sum_t = 0
def my_sum(items):
    if len(items) == 0:
        return 0
    global sum_t
    head, *tail = items
    return head + my_sum(tail)
print(my_sum(f))

0
1
[2, 3, 4]
5
15


In [3]:
# have a queue and keep the last n items
from collections import deque

f = deque(maxlen=3) # maxlen limits the number of elements and pops off older elements
f.append(1)
f.append(2)
f.append(3)
print(f)
f.append(4)
print(f) # This will pop 1 off the queue

deque([1, 2, 3], maxlen=3)
deque([2, 3, 4], maxlen=3)


In [4]:
#largest/smallest n items
# Creating a heapified structure and then popping elements off the heap
my_list = [1,5,2,3,5,7,1,6]
import heapq
heapq.heapify(my_list)
print(my_list)

# smallest n elements can be grabbed by popping off the heap
print(heapq.heappop(my_list))
print(heapq.heappop(my_list))
print(heapq.heappop(my_list))

print(my_list)

# separately, can also use nlargest and nsmallest functions
my_list = range(6)
print(heapq.nsmallest(3, my_list))
print(heapq.nlargest(3, my_list))

[1, 3, 1, 5, 5, 7, 2, 6]
1
1
2
[3, 5, 6, 5, 7]
[0, 1, 2]
[5, 4, 3]


In [5]:
# priority queue
import heapq

class MyQueue(object):
    def __init__(self):
        self.my_list = []
        self.index = 0
        
    def push(self, value, priority):
        # heappush does not allow for a keyfunction to specifiy priority.
        # instead we store a tuple which has priority as the first element
        # when comparing two tuples, it's in the order of the tuple elements
        # so priority takes precedence. index is also added in case two priorities 
        # are the same, we want to give preference to the element that was added first
        heapq.heappush(self.my_list, (priority, self.index, value))
        self.index = self.index + 1
    
    def pop(self):
        #index -1 to actually get at the value and not the priority or the index
        return heapq.heappop(self.my_list)[-1] 
    
my_q = MyQueue()
my_q.push('a',1)
my_q.push('b',3)
my_q.push('c',4)
my_q.push('d',2)
my_q.push('e',5)

print(my_q.pop())
print(my_q.pop())
print(my_q.pop())
print(my_q.pop())
print(my_q.pop())

a
d
b
c
e


In [6]:
# multidict
# collections.abc - mimic a dictionary
# let's do sensible things

from collections.abc import MutableMapping
from collections import defaultdict

class MyMultiDict(MutableMapping):
    def __init__(self):
        self._mydict = defaultdict(list)
    
    def __getitem__(self, key):
        return self._mydict[key]
    
    def __iter__(self):
        for key,value in self._mydict.items():
            for x in value:
                yield key, x
    
    def __len__(self):
        return [sum(x) for x in self._mydict.values()]
    
    def __delitem__(self, key):
        return self._mydict.pop(key)
    
    def __setitem__(self, key, value):
        self._mydict[key].append(value)
    
multi_dict = MyMultiDict()
multi_dict["a"] = 1
multi_dict["a"] = 2
print(multi_dict["a"])
print(multi_dict["b"])
print(multi_dict["b"])
multi_dict.pop("a")
print(multi_dict["a"])

[1, 2]
[]
[]
[]


In [7]:
# ordered dict to keep the order in which elements were inserted
# the built-in dictionary class does not have this guarantee

from collections import OrderedDict

In [8]:
# calculating with dictioanries
# most calculations should take a key function

my_dict = {"a" : 1, "b" : 3 , "c" : 5}

# max
print(max(my_dict.items(), key = lambda x : x[1]))

# min
print(min(my_dict.items(), key = lambda x : x[1]))

# sorting
print(sorted(my_dict.items(), key = lambda x : x[1]))

('c', 5)
('a', 1)
[('a', 1), ('b', 3), ('c', 5)]


In [9]:
# commonalities
# same keys, same values, etc

my_dict_1 = {"a" : 1, "b" : 3 , "c" : 5}
my_dict_2 = {"d" : 1, "b" : 5 , "f" : 3, "c" : 5}

print(my_dict_1.keys() & my_dict_2.keys()) # common keys
#print(my_dict_1.values() & my_dict_2.values()) # common values
print(my_dict_1.items() & my_dict_2.items()) # common items

# open question : why is list intersection not supported in python ?
# maybe because lists can contain non unique values?
# keys and items are inherently unique
print(my_dict_1.values())
print(my_dict_2.values())
print(type(my_dict_1.keys()))
print(type(my_dict_1.items()))
print(type(my_dict_1.values()))

help(type(my_dict_1.values()))
help(type(my_dict_1.keys()))
help(type(my_dict_1.items()))

{'c', 'b'}
{('c', 5)}
dict_values([1, 3, 5])
dict_values([1, 5, 3, 5])
<class 'dict_keys'>
<class 'dict_items'>
<class 'dict_values'>
Help on class dict_values in module builtins:

class dict_values(object)
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __repr__(self, /)
 |      Return repr(self).

Help on class dict_keys in module builtins:

class dict_keys(object)
 |  Methods defined here:
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iter__(self, /)
 |      Implement iter(s

In [10]:
# remove duplicates from a sequence
# conversion to a set removes the ordering

def dedupe(items):
    seen_set = set()
    for item in items:
        if item in seen_set:
            continue
        else:
            seen_set.add(item)
            yield item
            
dup_list = [1,2,3,4,1,1,1,1,2,2,3,4,2,2]
print([x for x in dedupe(dup_list)])

[1, 2, 3, 4]


In [11]:
# naming a slice
my_list = range(5)
first_3_elements = slice(0,3)

# this is still just another range
# That is pretty awesome!!!!
print(my_list[first_3_elements])
# in temrs of implementation, the __getitem__ function
# likely checks to see if the input is a slice 
# in which case it then re-returns an iterator

print(my_list[0:3]) # This also just returns a range
print(type(my_list[0:3])) # This also just returns a range

print(list(my_list[first_3_elements])) # force the expansion

#help(range)

range(0, 3)
range(0, 3)
<class 'range'>
[0, 1, 2]


In [12]:
# most frequent items
# any type of counting

from collections import Counter

my_list = [1,1,1,2,2,2,2,3,3,3,2,2,1,1,1,1]
counter = Counter(my_list)
print(counter.most_common()[0])
print(counter[2])
print(counter[3])
print(type(counter))

# counters have arithmetic operations available which is cool
my_other_list = [1]
counter_other = Counter(my_other_list)

counter_combined = counter + counter_other
print(counter[1])
print(counter_other[1])
print(counter_combined[1])

(1, 7)
6
3
<class 'collections.Counter'>
7
1
8


In [13]:
# sorting without native comparison
# use the keyfunc or the attrgetter method

from operator import attrgetter

class User(object):
    def __init__(self, id):
        self.id = id
        
    def __str__(self):
        return self.id
    
    def __repr__(self):
        return self.id
        
users = [User(x) for x in ["c", "a", "d"]]
print(sorted(users, key=lambda x : x.id))
print(sorted(users, key=attrgetter('id')))

[a, c, d]
[a, c, d]


In [14]:
from operator import itemgetter
from itertools import groupby

rows = [ {'id' : 3, 'group' : 1},
        {'id' : 4, 'group' : 2},
        {'id' : 5, 'group' : 1},
        {'id' : 1, 'group' : 2},
        {'id' : 2, 'group' : 1},
]

# the two methods are similar
rows.sort(key=itemgetter('group'))
#rows.sort(key=lambda x : x['group'])

# note groupby only works on already sorted rows
for group, items in groupby(rows, key=itemgetter('group')):
    print(group)
    for item in items:
        print(item)

1
{'id': 3, 'group': 1}
{'id': 5, 'group': 1}
{'id': 2, 'group': 1}
2
{'id': 4, 'group': 2}
{'id': 1, 'group': 2}


In [15]:
#filtering
my_list = range(5)
filtered_list = filter(lambda x : x > 3, my_list)
print(list(filtered_list))

# other itertools filters are  takewhile/dropwhile/filterfalse

[4]


In [16]:
# dictionary subset

my_dict = {'a' : 1 , 'b' : 3, 'c' : 5}
my_sub_dict = {key:value for key, value in my_dict.items() if value > 2}
print(my_sub_dict)

{'b': 3, 'c': 5}


In [17]:
# named tuples
from collections import namedtuple
MyTuple = namedtuple('MyTuple', ['id', 'name'])
tuple = MyTuple(3,4)
print(tuple)

MyTuple(id=3, name=4)


In [18]:
# generator expressions
sum(x**2 for x in range(3))

5

In [19]:
# merging dictionaries causes copies
# to deal with two dictionaries as though they are the same
# use chainmap

from collections import ChainMap

my_dict = {'a' : 1}
my_dict_2 = {'b' : 2, 'a' : 3}
merged = ChainMap(my_dict, my_dict_2)
print(merged)

# note if the dicts have common keys, the first dictionary takes
# precedence
print(merged['a'])

ChainMap({'a': 1}, {'b': 2, 'a': 3})
1


###  Chapter 2


In [20]:
# simple string split only takes in a single delimiter
import re

line = 'asdf fjdk; afed, fjek,asdf,      foo'
re.split(r'[;,\s]\s*', line)

['asdf', 'fjdk', 'afed', 'fjek', 'asdf', 'foo']

In [21]:
# starts with and endswith
my_list = 'abcd efgg aaa'
print(my_list.startswith('abc'))
print(my_list.startswith('def'))
print(my_list.endswith('def'))
print(my_list.endswith('aaa'))

True
False
False
True


In [22]:
# patterns

import re

text = 'Today is 11/27/2012. PyCon starts 3/13/2013.'

# note match requires matches from the start of the string
# search does not require this

print(re.search(r'\d+/\d+/\d+', text).group(0))
print(re.match(r'\d+/\d+/\d+', text)) # None

# practice is  to compile the regex if it will be re-used
com = re.compile(r'\d+/\d+/\d+')
print(com.findall(text))

# can use finditer to get an iterator
print([x.group(0) for x in com.finditer(text)])

11/27/2012
None
['11/27/2012', '3/13/2013']
['11/27/2012', '3/13/2013']


In [23]:
# replace with simple string replace
text = 'yeah, but no, but yeah, but no, but yeah'
print(text.replace('yeah', 'yes'))

# replace regex
import re

text = 'yeah, but no, but yeah, but no, but yeah'
print(re.sub(r'(yeah)', r'\1 dude', text)) # capture the yeah and replace with yeah dude

# callback for replace method
def rep_foo(match):
    return match.group(1) + " buddy"
print(re.sub(r'(yeah)', rep_foo, text)) # capture the yeah and replace with yeah dude

# case insensitive flag
text = 'yEAH, bUt No, but yEAh, but NO, bUt yEAh'
print(re.sub(r'(yeah)', r'\1 dude', text, flags=re.IGNORECASE)) # capture the yeah and replace with yeah dude


yes, but no, but yes, but no, but yes
yeah dude, but no, but yeah dude, but no, but yeah dude
yeah buddy, but no, but yeah buddy, but no, but yeah buddy
yEAH dude, bUt No, but yEAh dude, but NO, bUt yEAh dude


In [24]:
# discussions around unicode that are not useful
# discussions around regular expression edge cases not useful

In [25]:
# strip

text = " a boy was in the well "
print(text.lstrip())
print(text.rstrip())
print(text.strip())
print(text.replace(' ', '-'))

a boy was in the well 
 a boy was in the well
a boy was in the well
-a-boy-was-in-the-well-


In [26]:
# alignment
text = "Hello World"
print(text.ljust(20))
print(text.rjust(20))
print(text.center(20))
print(text.center(20, '='))


Hello World         
         Hello World
    Hello World     
====Hello World=====


In [27]:
# joining
text = ['a', 'b']
print(' '.join(text))

# use generators when able so 
# users can decide on how to join

def give_strings():
    yield 'a'
    yield 'b'

print(' '.join(give_strings()))

a b
a b


In [28]:
# format method
print('variable {a} will be substituted {}'.format("here", a=34))

variable 34 will be substituted here


In [29]:
import textwrap

# wrap text around a column length
text = "This is a long string which definitely is larger than 20 characters"
print(text)
print(textwrap.fill(text, 20))

This is a long string which definitely is larger than 20 characters
This is a long
string which
definitely is larger
than 20 characters


In [30]:
# working with xml and html (not useful)

In [31]:
# TODO: TOKENIZING AND PARSING (2.18/2.19) - large topics
# need to come back to this later

In [32]:
# byte strings vs text strings
# most of the operations works the same. use text if the 
# underlying data is text


###  Chapter 3 - Numbers/Dates/Times


In [33]:
print(round(1.23,1))
print(round(1.23,2))
print(round(100/3,5))


1.2
1.23
33.33333


In [34]:
a = 2.1
b = 4.2
print(a+ b)

6.300000000000001


In [35]:
from decimal import Decimal

a = Decimal('2.1')
b = Decimal('4.2')
c = a + b
print(c)

from decimal import localcontext

a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)
with localcontext() as ctx:
    ctx.prec = 4
    print(a/b)
    
# See the next code section
# to see how the precision value might be influenced
# within a context

6.3
0.7647058823529411764705882353
0.7647


In [36]:
# recollect how contexts are implemented
from contextlib import contextmanager


CURRENTLY_SAYING = 'a'


def says_depending_on_context():
    global CURRENTLY_SAYING
    return CURRENTLY_SAYING

@contextmanager
def switch_say(input_value):
    global CURRENTLY_SAYING
    old_saying = CURRENTLY_SAYING
    CURRENTLY_SAYING = input_value
    try:
        yield CURRENTLY_SAYING
    finally:
        CURRENTLY_SAYING = old_saying

print(says_depending_on_context())
with switch_say('b'):
    print(says_depending_on_context())

print(says_depending_on_context())

a
b
a


In [37]:
# formatting numbers using format
# format has a mini language (not currently useful)

number = 123.45555
print(format(number, '3.2f'))
print(format(number, '3.3f'))
print(format(number, '10.3f'))

123.46
123.456
   123.456


In [38]:
# oct, bi n and hexx
a = 1234
print(a)
print(bin(a))
print(hex(a))
print(oct(a))


# Note: This is just for formatting
# all of the underlying types are still floats
print(type(a))

b = 123.33
#print(bin(b)) # float objects cannot be represented as integers
#print(hex(b))
#print(oct(b))
print(type(b))

1234
0b10011010010
0x4d2
0o2322
<class 'int'>
<class 'float'>


In [39]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
int.from_bytes(data, 'little') # endian-ness

69120565665751139577663547927094891008

In [40]:
a = complex(2,3) # use constructor
print(a)

b = 3 + 5j # or the j suffix to numbers
print(b)

print(a+b)

print(a.real)
print(a.imag)
print(a.conjugate())
print(type(a))

(2+3j)
(3+5j)
(5+8j)
2.0
3.0
(2-3j)
<class 'complex'>


In [41]:
# inf and nan

a = float('inf')
b = float('-inf')
c = float('nan')

print(a)
print(b)
print(c)

print(a+45)
print(a-45)
print(b-45)
print(b+45)

print(float('inf')/float('inf'))
print(float('inf')/float('-inf'))

# nan simply propagates
print(c + 45) # all math operations on nan are nan

from math import isinf, isnan

print(isnan(c))
print(isinf(a))

inf
-inf
nan
inf
inf
-inf
-inf
nan
nan
nan
True
True


In [42]:
# fractions
from fractions import Fraction

a = Fraction(3,4)
b = Fraction(1,2)

print(a)
print(b)
print(a + b )
print(a * b )


3/4
1/2
5/4
3/8


In [43]:
# numpy Note: This will be the subject of the book:
# Python for data analysis. This is a starter

# need to install python3-numpy using apt-get
import numpy as np

ax = np.array([1,2,3,4])
ay = np.array([1,2,3,4])

print(ax + ay)
print(ax * 3)


large_grid = np.zeros(shape=(10000,10000), dtype=float)
print(large_grid + 2)
print(np.sin(large_grid + 2))

[2 4 6 8]
[ 3  6  9 12]
[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
[[0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]
 [0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]
 [0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]
 ...
 [0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]
 [0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]
 [0.90929743 0.90929743 0.90929743 ... 0.90929743 0.90929743 0.90929743]]


In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[0])
print(a + [1,1,1,1])
print(a[0:2]) # rows 0 and 1
print("====")
print(a[0:2, -1:]) # last column of rows 0 and 1
a[0:2, -1:] += 5
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[1 2 3 4]
 [5 6 7 8]]
====
[[4]
 [8]]
[[ 1  2  3  9]
 [ 5  6  7 13]
 [ 9 10 11 12]]


In [45]:
# matrices and linear algebra

import numpy as np
m = np.matrix([[1,2,3], [3,4,5], [5,6,7]])
print(m)

print(m.T) # transpose
print(m.I) # inverse
print(m.I * m) # float multiplication does not work here
print(m * m.I)
print("===============")
simple = np.matrix([[2,0], [0,2]])
print(simple)
print(simple.I)
print(simple.T)
print(simple.I * simple) # float mult works here and give sthe I matrix
print(simple * simple.I)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[1 3 5]
 [2 4 6]
 [3 5 7]]
[[ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]
 [-9.00719925e+15  1.80143985e+16 -9.00719925e+15]
 [ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]]
[[ -4. -20. -28.]
 [ -8.   0.   8.]
 [  4.   4.   0.]]
[[-2.  0. -2.]
 [ 0.  0. -8.]
 [ 0.  0.  0.]]
[[2 0]
 [0 2]]
[[0.5 0. ]
 [0.  0.5]]
[[2 0]
 [0 2]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [46]:
# random

import random
choices = [1,2,3,4]
print(random.choice(choices))
print(random.sample(choices,2))

random.shuffle(choices)
print(choices)

2
[4, 1]
[3, 4, 1, 2]


In [47]:
# datetime module
from datetime import timedelta, datetime

a = timedelta(days=2)
b = datetime.now()

print(b)
print(a+b)

2020-05-15 08:17:23.028475
2020-05-17 08:17:23.028475


In [48]:
# date tiem to string and back
from datetime import datetime
date_str = "2012-02-09"
y = datetime.strptime(date_str, "%Y-%m-%d")
print(y)

2012-02-09 00:00:00


In [49]:
# conversion of timezones using pytz
from datetime import datetime
from pytz import timezone, utc

now  = datetime.now()
print(now)
est = timezone('US/Eastern')
est_now = est.localize(now)
print(est_now)

# get time in india
print(est_now.astimezone(timezone('Asia/Kolkata')))

# get utc
print(est_now.astimezone(utc))

2020-05-15 08:17:23.046889
2020-05-15 08:17:23.046889-04:00
2020-05-15 17:47:23.046889+05:30
2020-05-15 12:17:23.046889+00:00


### Chapter 4

In [50]:
# using next instead of for
my_list = [1,2,3,4]

it = iter(my_list)
while True:
    try:
        print(next(it))
    except StopIteration:
        break        


1
2
3
4


In [51]:
# depth first iterations via generator and via iterator

from collections import deque

class Node(object):
    def __init__(self, value):
        self.value = value
        self.children = []
        
    def add_child(self, node):
        self.children.append(node)
    
    # Shoudl really not be properties of the node
    # but of the tree
    def breadth_first(self):        
        yield self        
        for x in self.children:
            deque.append(x)
            yield x
            
        
    def depth_first(self):
        for x in self.children:
            yield from x.depth_first()
        yield self
    
def test_cls(cls):
    node_parent = cls(0)
    node_child1 = cls(1)
    node_child2 = cls(2)
    node_child1_child1 = cls(3)
    node_child1_child2 = cls(4)
    
    node_child2_child1 = cls(5)
    node_child2_child2 = cls(6)
    
    node_parent.add_child(node_child1)
    node_parent.add_child(node_child2)
    
    node_child1.add_child(node_child1_child1)
    node_child1.add_child(node_child1_child2)
    
    node_child2.add_child(node_child2_child1)
    node_child2.add_child(node_child2_child2)
    
    print([x.value for x in node_parent.depth_first()])
    print([x.value for x in node_parent.breadth_first()])
    
cls = Node
#test_cls(cls)
    

In [52]:
a = [1,2,3,4]
print(list(reversed(a)))

[4, 3, 2, 1]


In [53]:
# implement iterators for classes to keep state around


In [54]:
# slicing on iterators is not possible since 
# no information is known about size and index and subscripting

it = (x for x in range(5))
#  error
#print(it[0:1])

# instead, islice from itertools creates an iterator object
# which does have all of these features
from itertools import islice
print(list(islice(it, 0, 2)))


[0, 1]


In [55]:
# discussions on dropwhile, permuations and enumerate 
# already covered in effective python

# discussions on chain, zip, zip_longest 

In [56]:
# sorted merge
import heapq

a = [1,3,4,5]
b = [0,2,6,7]
print(list(heapq.merge(a,b)))

[0, 1, 2, 3, 4, 5, 6, 7]


In [57]:
# Cool way to iterate:

import sys
with open("/etc/hosts", 'r') as f:
    
    # The iter method can take in a 0 argument lambda
    # and a sentinel value and create an iterable from it 
    # that keeps invoking the lambda until the sentinel value is 
    # returned
    for chunk in iter(lambda:f.read(100), ''):
        print(chunk)
    

127.0.0.1	localhost
127.0.1.1	rushi-study

# The following lines are desirable for IPv6 capable host
s
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnod
es
ff02::2 ip6-allrouters



### Chapter 5 (Files)


In [58]:
# basic file read/write stuff 
with open("/tmp/mytempfile", 'w') as f:
    f.write("hello")
    print("\nworld", file=f)

with open("/tmp/mytempfile", 'r') as f:    
    for line in f.readlines():
        print(line)


hello

world



In [59]:
# file like interface using string or bytes

from io import StringIO, BytesIO

s = StringIO()
s.write("abc")
print(s.getvalue())

print("new data ", file=s)
print(s.getvalue())

b = BytesIO()
b.write(b'Hello')
print(b.getvalue())
#print(b'new data ', file=b) # print does not work since it uses only strings
b.write(b'35')
b.write(b'0x34')
print(b.getvalue())


abc
abcnew data 

b'Hello'
b'Hello350x34'


In [60]:
# Using zipped files
import gzip

with gzip.open("/tmp/compressedfile", "wt") as f:
    f.write("hello")
    
with gzip.open("/tmp/compressedfile", "rt") as f:
    text = f.read()
    print(text)


hello


In [61]:
import sys
# reading fixed sized chunks
RECORD_SIZE = 1

with open("/tmp/fixed_sizes_files", "wb") as f:
    for x in range(3):        
        f.write(x.to_bytes(RECORD_SIZE, sys.byteorder))

# size of each int is 4 bytes
from functools import partial


with open("/tmp/fixed_sizes_files", "rb") as f:
    records = iter(partial(f.read, 1), b'')
    for x in records:
        print(int.from_bytes(x, sys.byteorder))

0
1
2


In [62]:
# re-usable pre-allocated buffers
import sys

preallocated_buffer = bytearray(20)

with open("/tmp/testfile", "wb") as f:
    for x in range(10):        
        f.write(x.to_bytes(1, sys.byteorder))
        
with open("/tmp/testfile", "rb") as f:
    print("num bytes:", f.readinto(preallocated_buffer))
    
print(preallocated_buffer)
print(preallocated_buffer[9])

num bytes: 10
bytearray(b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
9


In [63]:
# memory mapping fies ( TODO)
import os 
import mmap

required_size = 100
with open('/tmp/mmap_file', 'wb') as f:
    f.seek(required_size - 1)
    f.write(b'\x00')

fd = os.open('/tmp/mmap_file', os.O_RDWR)
m = mmap.mmap(fd, required_size, mmap.ACCESS_WRITE)
print(len(m))
# edit the memory
m[0:11] = b'Hello World'
print(m[0:21])
print(len(m))
m.flush()
m.close()

# Does not seem to be working ()
with open('/tmp/mmap_file', 'rb') as f:    
    print(f.read(11))


100
b'Hello World\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
100
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


In [64]:
import os

print(os.path.isfile("/etc/passwd"))
print(os.path.getsize("/etc/passwd"))
print(os.path.getmtime("/etc/passwd"))
print(os.path.isdir("/etc"))
print(os.path.islink("/usr/local/bin/python3"))
print(os.path.realpath("/usr/local/bin/python3"))

True
2772
1575206568.1707957
True
False
/usr/local/bin/python3


In [65]:
import os

print([x for x in os.listdir("/")])

# regex search
import glob
print(glob.glob('/ho*/'))

['srv', 'lib', 'boot', 'swapfile', 'media', 'lib32', 'snap', 'etc', 'tmp', 'opt', 'libx32', 'sys', 'mnt', 'usr', 'root', 'lost+found', 'proc', 'run', 'home', 'sbin', 'var', 'dev', 'lib64', 'bin', 'cdrom']
['/home/']


In [66]:
# couple of articls around changing the encoding of files
# that is un-interesting to me

In [67]:
# converting fds to python files

import os

fd = os.open("/tmp/tmpfile", os.O_CREAT | os.O_WRONLY)
f = open(fd, "w")
f.write("hello")
f.close()

fd = os.open("/tmp/tmpfile", os.O_RDONLY)
f = open(fd, "r")
print(f.readlines())
f.close()


['hello']


In [68]:
from tempfile import TemporaryFile, TemporaryDirectory

with TemporaryFile('w+t') as t:
    t.write("anc")
# file is deleted at this point


In [69]:
# need to read up on pickly separately

###  Chapter 6

In [70]:
# csv reader 

headers = ['Symbol','Price','Date','Time','Change','Volume']
rows = [('AA', 39.48, '6/11/2007', '9:36am', -0.18, 181800),
        ('AIG', 71.38, '6/11/2007', '9:36am', -0.15, 195500),
        ('AXP', 62.58, '6/11/2007', '9:36am', -0.46, 935000),]


import csv
from tempfile import TemporaryFile

# if we have headers and a set of rows
with TemporaryFile('w+t') as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    for row in rows:        
        writer.writerow(row)
    
    f.seek(0)
    for line in f.readlines():
        print(line)
        
    # now read it back
    f.seek(0)
    reader = csv.DictReader(f)
    for row in reader:
        print(row)
    

Symbol,Price,Date,Time,Change,Volume

AA,39.48,6/11/2007,9:36am,-0.18,181800

AIG,71.38,6/11/2007,9:36am,-0.15,195500

AXP,62.58,6/11/2007,9:36am,-0.46,935000

OrderedDict([('Symbol', 'AA'), ('Price', '39.48'), ('Date', '6/11/2007'), ('Time', '9:36am'), ('Change', '-0.18'), ('Volume', '181800')])
OrderedDict([('Symbol', 'AIG'), ('Price', '71.38'), ('Date', '6/11/2007'), ('Time', '9:36am'), ('Change', '-0.15'), ('Volume', '195500')])
OrderedDict([('Symbol', 'AXP'), ('Price', '62.58'), ('Date', '6/11/2007'), ('Time', '9:36am'), ('Change', '-0.46'), ('Volume', '935000')])


In [71]:
from tempfile import TemporaryFile
#help(TemporaryFile)

In [72]:
import csv
#help(csv)

In [73]:
import json

# serialize/deserialize an object to a file

# keep a dictionary of known classes
# when serializing, make sure to keep the name of the class around
# when de-serializing, create a new object without calling __init__ 
# and instead using __new__ and then filling up the attributes


class TestClass1(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def foo(self):
        pass

class TestClass2(object):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def bar(self):
        pass

class_registry = {'TestClass1' : TestClass1, 
                  'TestClass2' : TestClass2}

# problem is two dictionaries are loaded separately
def serialize(f, obj_list):
    full_list = []
    for obj in obj_list:
        my_dict = obj.__dict__
        my_dict.update({'name' : obj.__class__.__name__})
        print(my_dict)
        full_list.append(my_dict)
    
    json.dump(full_list, f)

def deserialize(f):
    out_dict = json.load(f)
    print(out_dict)
    elements = []
    for element in out_dict:
        cls = class_registry[element['name']]
        obj = cls.__new__(cls)
        obj.__dict__ = element
        elements.append(obj)
    return elements

test_class1 = TestClass1(1,2)
test_class2 = TestClass2(3,4,5)

with TemporaryFile('w+t') as f:
    serialize(f, [test_class1, test_class2])
    f.seek(0)
    my_class1, my_class2 = deserialize(f)
    print(my_class1.a)
    print(my_class1.b)
    print(my_class2.a)
    print(my_class2.b)
    print(my_class2.c)
    

print(test_class1.__dict__)
print(test_class2.__dict__)


{'a': 1, 'b': 2, 'name': 'TestClass1'}
{'a': 3, 'b': 4, 'c': 5, 'name': 'TestClass2'}
[{'a': 1, 'b': 2, 'name': 'TestClass1'}, {'a': 3, 'b': 4, 'c': 5, 'name': 'TestClass2'}]
1
2
3
4
5
{'a': 1, 'b': 2, 'name': 'TestClass1'}
{'a': 3, 'b': 4, 'c': 5, 'name': 'TestClass2'}


In [74]:

# classmethods take in a class and either create them or 
# execute a known method on them which returns whatever is needed.
# metaclasses are used to validate and register classes
# each time a new class is created, metaclasses methods
# get invoked first

In [75]:
class Test():
    def __init(self):
        pass
    
test = Test()
print(test.__class__.__name__)

Test


In [76]:
# xml parsing and url request

from urllib.request import urlopen
from xml.etree.ElementTree import parse

u = urlopen('http://planet.python.org/rss20.xml')
doc = parse(u)
print(type(doc))

for item in doc.iterfind('channel/item'):
    print(item.findtext('title'))
    print(item.findtext('pubDate'))
    print(item.findtext('link'))
    print()


<class 'xml.etree.ElementTree.ElementTree'>
Reuven Lerner: Today’s lesson in “Python for non-programmers”: Dictionaries
Fri, 15 May 2020 09:03:26 +0000
https://lerner.co.il/2020/05/15/todays-lesson-in-python-for-non-programmers-dictionaries/

Python Software Foundation: Lightning Talks Part 1 - Python Language Summit 2020
Thu, 14 May 2020 14:03:46 +0000
http://feedproxy.google.com/~r/PythonSoftwareFoundationNews/~3/cWtcQjdVcnQ/lightning-talks-part-1.html

Python Software Foundation: The 2020 Python Language Summit
Thu, 14 May 2020 13:48:48 +0000
http://feedproxy.google.com/~r/PythonSoftwareFoundationNews/~3/plH83v899Ww/the-2020-python-language-summit.html

Python Software Foundation: Lightning Talks Part 2 - Python Language Summit 2020
Thu, 14 May 2020 13:46:08 +0000
http://feedproxy.google.com/~r/PythonSoftwareFoundationNews/~3/5P9XTL57fNU/lightning-talks-part-2.html

Python Circle: Displaying custom 404 error (page not found) page in Django 2.0
Thu, 14 May 2020 13:44:55 +0000
https:/

In [77]:
# read and write binary records

from struct import Struct
from tempfile import TemporaryFile

with TemporaryFile() as f:
    records = [ (1, 2.3, 4.5),(6, 7.8, 9.0),(12, 13.4, 56.7) ]
    struct = Struct('<idd') # little endian, int, double, double
    for r in records:
        f.write(struct.pack(*r))
    
    f.seek(0)
    for record_data in iter(lambda:f.read(struct.size), b''):        
        record = struct.unpack(record_data)
        print(record)

(1, 2.3, 4.5)
(6, 7.8, 9.0)
(12, 13.4, 56.7)


In [78]:
# complicated look into packing and unpacking 
# using metaclasses (can be used as a reference )

In [79]:
# pandas. Will dig more deeply in the book
# python for data analysis


###  Chapter 7 - functions


In [80]:
# any number of input args
def foo(*args):
    print(*args)
    
foo(1)
foo(1,2)

def bar(**kwargs):
    print(kwargs)
    print(kwargs.get('a'))
    
bar(a = 3, b = 4)

1
1 2
{'a': 3, 'b': 4}
3


In [81]:
# function annotations

def add(x:int, y:int) -> int:
    return x+y
help(add)

Help on function add in module __main__:

add(x: int, y: int) -> int



In [82]:
# return multiple results
def foo():
    return list(range(4))

# get the last value
*_,last = foo()
print(last)

3


In [83]:
# do not use mutable objects as default values in functions
# these are shared across function calls !!

# !!NO
def foo(a = []):
    return a


In [84]:
# lambda capture

x = 10 
a = lambda y: x+y
x = 20
print(a(1)) # returns 21 instead of 11 (current value of x is used)

x = 10
b = lambda y,x=x: x + y # sets the default value of x to x
x = 20
print(b(1))

21
11


In [85]:
# partial functool which fixes some function arguments
# sort of like std::bind in c++

# function signature of foo takes in 4 arguments.
# let's say argument d is to tweak logging and
# when not passed, does not log
def foo(a,d = None):
    if d is None:
        return
    else:
        print(a)
    
# lets say we have a different function which takes a callback
def bar(callback):
    callback(3)
    
# we want to use foo as callback but also want to log
bar(foo) # will not log

from functools import partial 

# we can fix the foo argument by doing this:
bar(partial(foo, d=True)) # partial returns a function with the arguments fixed

# TODO: Implement partial    
    

3


In [86]:
# methods of supplying callbacks with context

def foo(callback):
    callback()

# we want callback to keep track of the number of times
# it's been invoked


# method 1
# use a class
class CallbackClass(object):
    def __init__(self):
        self.times = 0
    
    def __call__(self):
        self.times +=1
        return self.times

callback_instance = CallbackClass()
for x in range(5):
    foo(callback_instance)
print(callback_instance.times)


# method 2
# use a wrapper function which has state

def cb_wrapper(times):
    def cb():
        nonlocal times
        times[0] += 1
    return cb

times = [0]
cb = cb_wrapper(times)
for x in range(5):
    foo(cb)

print(times)

# method 3 
# use coroutines

sequence = 0 
def make_coroutine_handler():    
    def handler():
        global sequence
        while True:
            response = yield
            sequence += 1
    return handler()

handler = make_coroutine_handler()
next(handler)
for x in range(5):
    foo(partial(handler.send, 0))

print(sequence)

# use partial
# create a mutable that can be passed to function
# cannot pass simple ints since they are not mutable
# only lists, dicts, sets and custom classes are mutables
# int, float, str, tuple are not mutable
class SeqCounter(object):
    def __init__(self):
        self.seq = 0
        
from functools import partial
def counted_callback(seq_counter):
    seq_counter.seq += 1

seq_counter = SeqCounter()
for x in range(5):
    foo(partial(counted_callback, seq_counter))
print (seq_counter.seq)

5
[5]
5
5


In [87]:
# crazy apply_asyn callbacks (TODO)
# for now, no point in trying to figure out exact workings

In [88]:
# accessing closure variables

def sample():
    n = 0
    def func():
        pass
    def get_n():
        nonlocal n
        return n    
    def set_n(a):
        nonlocal n
        n = a
    func.get_n = get_n # these are function attributes
    func.set_n = set_n
    return func

# function instance is created
func = sample()

# function attributes can now be accessed
print(func.get_n())
func.set_n(3)
print(func.get_n())

0
3


### Chapter 8 - Classes and Objects

In [89]:
# __repr__ and __str__

class MyClass(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b
    
    # __repr__ is called by repr() which is an inbuilt function
    # which is used when evaluating or inspecting values.
    # __str__ is used when printing 
    # an object or during a call to format
    def __repr__(self):
        return "MyClass({0.a},{0.b})".format(self)
    
    def __str__(self):
        return "({0.a} and {0.b})".format(self)
    
my_class = MyClass(1,2)
print(str(my_class))
print(repr(my_class))

# evaluate the repr string to create a new object
new_class = eval(repr(my_class))
print(new_class.a)

(1 and 2)
MyClass(1,2)
1


In [90]:
# formatting 
class A(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def __format__(self, code):
        if code == '1':
            return "A: {0.a} B: {0.b}".format(self)
        else:
            return "B: {0.b} A: {0.a}".format(self)
        
a = A(1,2)
print(format(a, '1'))
print(format(a, '0'))

A: 1 B: 2
B: 2 A: 1


In [91]:
# use __slots__ to create compact instances


In [92]:
# class properties

class A(object):
    def __init__(self, a):
        self._a = a
    
    @property
    def a(self):
        print("getting a")
        return self._a
    
    # note: all three functions must be called the same
    @a.setter
    def a(self, a):
        print("setting a")
        self._a = a
    
    @a.deleter
    def a(self):
        print("deleting a")
        del self._a
    
a = A(2)
print(a.a)
a.a = 5
del a.a # fully deletes the attribute and the instance no longer has it
#print(a.a) # this will get an attribute error

getting a
2
setting a
deleting a


In [93]:
# descriptors

class MyDescriptor(object):
    def __init__(self, name):
        print("initializing descriptor")
        self.name = name
    
    def __get__(self, instance, cls):
        print("getting value: ", instance, cls.__name__)
        if instance is None:
            return self
        else:
            return instance.__dict__[self.name]
        
    def __set__(self, instance, value):
        print("setting value")
        instance.__dict__[self.name] = value
        
    def __delete__(self, instance):
        print("deleting value")
        del instance.__dict__[self.name]
        
class UsesDescriptors(object):
    z1 = MyDescriptor('a') # uses an instance with name 'a'
    z2 = MyDescriptor('b')
    
    def __init__(self, a1, b1):        
        # describes the class attribute
        # call translates to __get__(z1, None, UsesDescriptors)
        # returns a type mydescriptor since instance is None
        print(type(UsesDescriptors.z1))
        self.z1 = a
        
        # describes the instance attribute
        # call translates to __get__(z1, self, UsesDescriptors)
        # cannot return a value since self.__dict__ does not have
        # this key
        #print(type(self.z1)) # in this case , the __get__ ,
        
        # first looks up the variable in __dict__
        # if not found, uses the __getattr__ method
        # to see if an instance can be created.
        #print(type(self.a))
        
        #https://docs.python.org/3/reference/datamodel.html#descriptors
        # is a useful read around descriptors
        # a.x results in type(a).__dict__['x'].__get__(a, type(a))
        # this occurs only if an instance of the descriptor class 
        # appears in the class dictionary
        
        # becase of the lines:
        #  z2 = MyDescriptor('b'); z1 and z2 are put in the classes's dictionary
        # since z1 and z2 contains the __(get|Set|delte)__ methods, all future access to 
        # variables named z1 and z2 will now go through the descriptor class
        # self.z1 will first look through the instance dictionary, then the class dictionary.
        # it will find it in the class dictionary and will also find that the instance
        # implements the descriptor protocol after which python will override the access and setting of
        # this variable to be via the descriptor class
        
u = UsesDescriptors(1,2)
print(u.z1)

initializing descriptor
initializing descriptor
getting value:  None UsesDescriptors
<class '__main__.MyDescriptor'>
setting value
getting value:  <__main__.UsesDescriptors object at 0x7fe8db4eae50> UsesDescriptors


In [94]:
# class attributes can be created at runtime
# first looks at the __dict__; 
# python attribute errors are invoked if the object does not 
# already exist and one is not trying to set it but rather trying
# to access it.
class A(object):
    def __init__(self):
        pass
    
a = A()
print(hasattr(a, 'r'))

a.r = 4 # translated to setattr(a, 'r', 4)
print(a.r) # translated to getattr(a, 'r') which can fail
# we can override getattr to always call setattr and cause this to pass
print(hasattr(a, 'r'))

False
4
True


In [95]:
# abstract classes

from abc import abstractmethod, ABCMeta
# ABCMeta disallows an abstract class from being instantiated
# abstractmethod forces other classes implementing the interfacing
# to implment these methods

class A(metaclass=ABCMeta):
    
    @abstractmethod
    def method1():
        pass
    
    @abstractmethod
    def method2():
        pass
    
    
class B(A):
    def __init__():
        super(B, self).__init__()

try:
    b = B()
except TypeError as e:
    print(e)
    
class C(A):
    def __init__(self):
        super(C, self).__init__()
    
    def method1():
        pass
    
    def method2():
        pass
    
c = C()


Can't instantiate abstract class B with abstract methods method1, method2


In [96]:
# writing a decorator

def decor(func):
    print("hello")
    print(type(func))
    def func_wrap(*args, **kwargs):
        # * and ** are the unpacking arguments
        # these should be unpacked when forwarding
        # so that the inner function can process correctly
        # if these are not unpacked, args and kwargs would 
        # be the first two arguments instead of the unpacked 
        # sequences of arguments
        func(*args, **kwargs)
    return func_wrap
    
@decor
def foo():
    pass

foo()

hello
<class 'function'>


In [97]:
# topic on doing type checking using 
# descriptor protocolo and metaclasses or function decorators


In [98]:
# topic on collections' abstract base classes

In [99]:
# delegation via __getattr__ and __setattr__
# as an alternative to inheritance

class A(object):
    def __init__(self, a):
        self.a = a
        
class LoggingProxy(object):
    def __init__(self, inner_object):
        # this is problematic since this also invokes the setter
        # method. We need to somehow disable this
        self._object = inner_object
    
    def __getattr__(self, key):
        print("getting key", key)
        if key.startswith('_'):
            return super().__getattr__(self, key)
        else:
            return getattr(self._object, key)
    
    def __setattr__(self, key, value):
        print("setting key", key)
        if key.startswith('_'):
            super().__setattr__(key, value)
        else:        
            setattr(self._object, key, value)
    
    
a = A(3)
lp = LoggingProxy(a)

print(lp.a)
lp.b = 5
print(lp.b)

setting key _object
getting key a
3
setting key b
getting key b
5


In [100]:
# use class method to support alternate constructirs

class Date(object):
    def __init__(self, year, month, day):
        self.year = year
        # so on...
        
    @classmethod
    def today(cls):
        return Date(0,0,0)
    
random_date = Date(1,2,3)
today_date = Date.today()

In [101]:
# use of __new__ to create bare uninitialized data
# this is useful when deserializing data from files, etc

class A():
    def __init__(self, a):
        self.a = a
        
a = A.__new__(A)
a.a = 5
print(a.a)

5


In [102]:
# state transition by modifying self.__class__ 
# or an inner object entirely

# class A needs to constantly check the state
# to run it's methods.
class A(object):
    def __init__(object):
        self._state = '0'
        
    def method1(self):
        if self_state != '1':
            raise RuntimeError("invalid state")
        else:
            pass
            
    def method2(self):
        if self_state != '2':
            raise RuntimeError("invalid state")
        else:
            pass
        

# alternatively, class A could look like:
from abc import ABCMeta, abstractmethod

class State(metaclass=ABCMeta):
    @abstractmethod
    def method1(self):
        pass
    
    @abstractmethod
    def method2(self):
        pass

class State1(State):
    
    def method1(self):
        # do thing
        print("Hello")
        
    def method2(self):
        raise RuntimeError("Cannot do thing")
        
class State2(State):
    
    def method1(self):
        # do thing
        raise RuntimeError("Cannot do thing")
        
    def method2(self):
        print("Hello")
        
class A2(object):
    def __init__(self):
        self._state = State1()
        
    def method1(self):
        self._state.method1()
        
    def method2(self):
        self._state.method2()
        
    def state_switch(self):
        self._state = State2()

In [103]:
# visitor pattern using dynamically generated method names
# which are then invoked using getattr method.


# also explained is the use of yield in large data structures

In [104]:
# weak references to cause garbage collection for cyclic objects

In [105]:
# using caches to return instances of classes
# that were created using the same arguments (factories that return same instance)

### Chapter 9 - Metaprogramming

In [106]:
# decorators -- again -- done this already

In [107]:
# use functools.wraps to preserve the metadata like name, doc string and annotations
# unwrap a decorator using __wrapped__ on the decorated function object
# decoratora can also take additional arguments


In [108]:
# differences between decorators taking arguments and those that don't

# wrapper takes no arguments
def logged1(func):
    print("decorator not taking options")
    def wrapper(*args, **kwargs):
        func(*args, **kwargs)
    return wrapper

# wrapper that does take arguments:
# this wrapper does not get a function passed in.
# instead, it needs to return a decorator which takes in a function

# first invocation without a func argument should return a function
# object which takes a function objection and has all other args fixed

# second invocation should return a function that takes actual
# arguments
def logged(func=None, a=None, b = None):
    if func is None:
        print("first invocation of decorator taking options")
        return partial(logged, a=a, b=b) # fix the other arguments
    print("decorator taking options")
    def wrapper(*args, **kwargs):
        func(*args, **kwargs)        
    return wrapper

@logged1
def foo():
    pass

@logged(a=3, b=4)
def bar():    
    pass

foo()
bar()
# call sequence for bar is 
# bar()->logged with func=None func(a=3, b=4) -> partial func with func argument not None
# ->actual barcode

decorator not taking options
first invocation of decorator taking options
decorator taking options


In [109]:
# 9.7 -> 9.12 (Decorator magic)
# interesting use case of function decorators to enforece 
# the types of the function argument

# uses the inspect module and the signature class 

#(TODO) May need a revisit

In [110]:
# Read through rest of chapter 9 which dealt with somewhat esoteric topics


### Chapter 10 - Module (Just a read through and to be used as a reference)

###  Chapter 13 - Shell util scripts (Just a read through + usage of shutil library)

### Chapter 14 - Testing (Just a read through)

###  Chapter 11 - Networking
Most of the topics here usually have a better alternative in the form of librarires. For now, just a read through

###  Chapter 15 - C Modules


In [111]:
import ctypes
import os

# note: there is a limitation to how the load stuff works
# if a module is already loaded into the python interpreter,
# there is no easy way to unload it so changes can be made to the module and 
# for it to be re-run.

# this is bad since if while testing, changes are made to the modules,
# the python interpreter keeps them around.
# This is especially an issue in jupyter notebook since the interpreter never
# really goes down !!

# See here: https://bugs.python.org/issue14597

_path = "/home/rushi/dev/git/python/c_module/libsample4.so"
_mod = ctypes.cdll.LoadLibrary(_path)

_simple_path = "/home/rushi/dev/git/python/c_module/libadder2.so"
_simple_mod = ctypes.cdll.LoadLibrary(_simple_path)

print(_simple_mod.addTwo)
print(_mod.gcd)

# simple function taking two ints and returning an int
gcd = _mod.gcd
gcd.argtypes = (ctypes.c_int, ctypes.c_int)
gcd.restype = (ctypes.c_int)
print(gcd(10,12))

# function which takes in a pointer for a result
_divide = _mod.divide
_divide.argtypes = (ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_int))
_divide.restype = (ctypes.c_int)

def divide_wrapper(x,y):
    rem = ctypes.c_int()
    quot = _divide(x,y,rem)
    return quot, rem.value

print(divide_wrapper(5,2))

# using c structures 
# requires a class to be specified which can be passed
# in.
class Point(ctypes.Structure):
    _fields_ = [('x', ctypes.c_double),
                 ('y', ctypes.c_double)]

distance_func = _mod.distance
distance_func.argtypes = (ctypes.POINTER(Point), ctypes.POINTER(Point))
distance_func.restype = ctypes.c_double

p1 = Point(1,2)
p2 = Point(0,0)
print(distance_func(p1,p2))

2
(2, 1)
2.23606797749979


In [116]:
# write a handcrafted extension module directly using pythong C API
import sys
sys.path.append("/home/rushi/dev/git/python/c_module")
import sample_extension

# NOTE: Need to restart the entire interpreter if the load 
# does not work. Otherwise the module remains loaded in
# the interpreter and it won't work, even with the changes

print(sample_extension)
print(help(sample_extension))
print(dir(sample_extension))

print(sample_extension.addThree(1,2,3))

<module 'sample_extension' from '/home/rushi/dev/git/python/c_module/sample_extension.cpython-37m-x86_64-linux-gnu.so'>
Help on module sample_extension:

NAME
    sample_extension - sample extension module

FUNCTIONS
    addThree(...)
        Adds three numbers together

FILE
    /home/rushi/dev/git/python/c_module/sample_extension.cpython-37m-x86_64-linux-gnu.so


None
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'addThree']
6


In [ ]:
# Note: the rest of the topics in this chapter 
# are more for reference rather than implementation
# It might be better to use SWIG or other tools to wrap C into python